import web3 from './web3'

const abi = [{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor","signature":"constructor"},{"constant":false,"inputs":[],"name":"enter","outputs":[],"payable":true,"stateMutability":"payable","type":"function","signature":"0xe97dcb62"},{"constant":true,"inputs":[],"name":"getAllPlayers","outputs":[{"internalType":"address payable[]","name":"","type":"address[]"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xefa1c482"},{"constant":true,"inputs":[],"name":"getBalance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x12065fe0"},{"constant":true,"inputs":[],"name":"getManager","outputs":[{"internalType":"address","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xd5009584"},{"constant":true,"inputs":[],"name":"getPlayersCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xa76594bf"},{"constant":true,"inputs":[],"name":"manager","outputs":[{"internalType":"address","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x481c6a75"},{"constant":false,"inputs":[],"name":"pickWinner","outputs":[],"payable":true,"stateMutability":"payable","type":"function","signature":"0x5d495aea"},{"constant":true,"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"players","outputs":[{"internalType":"address payable","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xf71d96cb"},{"constant":false,"inputs":[],"name":"refund","outputs":[],"payable":true,"stateMutability":"payable","type":"function","signature":"0x590e1ae3"}]
const address = '0x962a9289b576F1E37F3432d828FeAa2C43A2267C'

const lottery = new web3.eth.Contract(abi, address)

export default lottery


